
[font] 
  normal = { family = "Fira Mono  Nerd  Font", style = "Regular" }
  size = 10.0

[window]
  decorations = "Buttonless"
  # opacity = 0.6
  blur = true 

# padding = { x = 3, y = 0 }

[scrolling]
  history = 5000


[env]
  TERM = "xterm-256color"

[selection]
  save_to_clipboard = true


[mouse]
  hide_when_typing = true

[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/themes/themes/catppuccin-mocha.toml"
  # "~/.config/alacritty/catppuccin/catppuccin-mocha.toml"
  "~/.config/alacritty/bruvbox.toml"
  # "~/.config/alacritty/themes/themes/nightfox.toml"
  # "~/.config/alacritty/themes/themes/gruvbox.toml"
]
# add_newline = false
# 
# [character]
# success_symbol = '[ #](bold green)'
# error_symbol = "[ x](bold red)"
# vicmd_symbol = "[ V](bold green)"
# 
# [git_status]
# disabled = false
# 
# [git_commit]
# commit_hash_length = 7
# tag_disabled = false
# only_detached = false
# 
# [battery]
# disabled = true
# 
# [python]
# disabled = true
# 
# [cmake]
# disabled = true
# 
# [directory]
# read_only = "(read only)"
# 
# [git_metrics]
# disabled = false
# format = '([+$added]($added_style)) ([-$deleted]($deleted_style)) '
